---
steps:
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - -b
      - main
      - https://github.com/aparnanashte/genGi.git
      - /workspace/test/
  - name: maven:3.8.3-openjdk-17
    entrypoint: mvn
    args:
      - clean
      - install
  - name: openjdk:17
    entrypoint: java
    args: -cp /workspace/target/bug-api-0.0.1-SNAPSHOT.jar - com.bug.api.BugkApiApplication REPOSITORY_PATH
env:
  REPOSITORY_PATH: ${{ github.workspace }}
options:
  logging: CLOUD_LOGGING_ONLY
