---
steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone','-b','main', 'https://github.com/aparnanashte/genGi.git']
  - name: gcr.io/cloud-builders/mvn
    args: ['clean', 'install']
    dir: /workspace/genGi
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - europe-west3-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}
      - /workspace/genGi/
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - europe-west3-docker.pkg.dev/${_PROJECT_ID}/gengi1/${_IMAGE_NAME}
substitutions:
  _IMAGE_NAME: gengi
  _PROJECT_ID: glb-fs-wgh-app-dev
  _REPO_NAME: gengi1
options:
  logging: CLOUD_LOGGING_ONLY
