---
steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone','-b','main', 'https://github.com/aparnanashte/genGi.git']
  - name: gcr.io/cloud-builders/mvn
    args: ['clean', 'install']
    dir: /workspace/genGi
    run: |
        java -jar target/bug-api-0.0.1-SNAPSHOT.jar "genrate junit for bug class"
options:
  logging: CLOUD_LOGGING_ONLY
