---
steps:
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - -b
      - main
      - https://github.com/aparnanashte/genGi.git
  - name: maven:3.8.3-openjdk-17
    entrypoint: mvn
    args:
      - clean
      - install
     
options:
  logging: CLOUD_LOGGING_ONLY
