---
steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone','-b','main', 'https://github.com/aparnanashte/genGi.git']
  - name: gcr.io/cloud-builders/mvn
    args: ['clean', 'install']
    dir: /workspace/genGi
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - europe-west3-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}
      - /workspace/genGi/
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - europe-west3-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'gcr.io/glb-fs-wgh-app-dev/gengi', 'java', '-jar', 'target/bug-api-0.0.1-SNAPSHOT.jar', 'test case generation for Bug class', 'AIzaSyDLdXcMmjvLlvTEDwMeO1DR-8iYBjU6SFI', '500']
substitutions:
  _IMAGE_NAME: gengi
  _PROJECT_ID: glb-fs-wgh-app-dev
  _REPO_NAME: gengi1
options:
  logging: CLOUD_LOGGING_ONLY
