---
steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone','-b','main', 'https://github.com/aparnanashte/genGi.git']
  - name: gcr.io/cloud-builders/mvn
    args: ['clean', 'install']
    dir: /workspace/genGi
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['exec:java', '-Dexec.mainClass=com.bug.api.TextInput', '-Dexec.args="genrate junit for bug class"', '-Dclasspath=target/classes']
options:
  logging: CLOUD_LOGGING_ONLY
