---
steps:
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - -b
      - main
      - https://github.com/aparnanashte/genGi.git
  - name: maven:3.8.3-openjdk-17
    args:
      - clean
      - package
      - -DskipTests=true
  - name: openjdk:17
    entrypoint: java
    args:
      - -jar
      - /root/.m2/repository/com/bug-api/bug-api/0.0.1-SNAPSHOT/bug-api-0.0.1-SNAPSHOT.jar
options:
  logging: CLOUD_LOGGING_ONLY
