---
steps:
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - -b
      - main
      - https://github.com/aparnanashte/genGi.git
  - name: maven:3.8.3-openjdk-17
    entrypoint: mvn
    args:
      - clean
      - install
  - name: openjdk:17
    entrypoint: java
    args:
      - -jar
      - /workspace/target/bug-api-0.0.1-SNAPSHOT.jar
      - com.bug.api.BugkApiApplication
     

  - name: 'gcr.io/cloud-builders/bash'
    args: ['-c', 'kill $(pgrep -f "java -jar/workspace/target/bug-api-0.0.1-SNAPSHOT.jar")']
options:
  logging: CLOUD_LOGGING_ONLY
