steps:
  - name: maven:3.8.3-openjdk-17
    entrypoint: mvn
    args:
      - clean
      - install
  - name: openjdk:17
    entrypoint: java
    args:
      - -jar
      - /workspace/target/bug-api-0.0.1-SNAPSHOT.jar
      - com.bug.api.BugkApiApplication "Genrate Junit Test case for
        com.bug.api.model.domain.Bug java class along with import statement"
options:
  logging: CLOUD_LOGGING_ONLY
