---
steps:
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - -b
      - main
      - https://github.com/aparnanashte/genGi.git
  - name: gcr.io/cloud-builders/mvn
    args:
      - clean
      - install
    dir: /workspace/genGi
  - name: gcr.io/cloud-builders/java
    args: ['-jar', '/root/.m2/repository/com/bug-api/bug-api/0.0.1-SNAPSHOT/bug-api-0.0.1-SNAPSHOT.jar', 'genrate junit for bug class']  
options:
  logging: CLOUD_LOGGING_ONLY
