steps:
- name: gcr.io/cloud-builders/git
  args: clone -b main https://github.com/aparnanashte/genGi.git
  status: ALREADY_EXISTS  # Allow cloning to skip if repository exists

- name: maven:3.8.3-openjdk-17
  entrypoint: mvn
  args: clean install
  dir: ${{ github.workspace }}/genGi
  status: FAILURE  # Stop execution if Maven build fails

- name: openjdk:17
  entrypoint: 'sh'
  args: -c
    |
      cd ${{ github.workspace }}/genGi
      java -cp ./workspace/target/bug-api-0.0.1-SNAPSHOT.jar com.bug.api.BugkApiApplication
  options:
  logging: CLOUD_LOGGING_ONLY
